version: 2
jobs:
  build:
    docker:
      - image: docker:edge-git
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          cd .circleci
          docker login -u terrorjack -p $DOCKER_PASS
          docker build -t terrorjack/chromebox:pixie .
          docker push terrorjack/chromebox:pixie
